### ISSUE TITLE
The kas repo identifier 'this' leads to confusion if used in a downstream layer

### ISSUE THREAD

**Issue by gylstorffq** [siemens/mtda#87]
An downstream ISAR project needs to use the following yml configuration for extending from the mtda ISAR layer.
```
header:
  version: 10
  includes:
    - repo: this
      file: kas/mtda-qemu-amd64.yml
repos:
  hardware-test-dispatcher:

  this:
    url: https://github.com/siemens/mtda.git
    refspec: master

```
I would recommend to rename `this` to `mtda` in  [kas/mtda-nanopi-neo](https://github.com/siemens/mtda/blob/master/kas/mtda-nanopi-neo.yml) and [kas/mtda-qemu-amd64](https://github.com/siemens/mtda/blob/master/kas/mtda-qemu-amd64.yml).
